spring:
  cloud:
    stream:
      bindings:
        #防止重复队列存在重复消息
        pre_send_sms_topic:                # 队列名称
          group: pre_send_sms_topic        # 队列组名称
      # 实现手动ACK
      rabbit:
        bindings:
          myMessage:
            pre_send_sms_topic:
              acknowledgeMode: MANUAL
  rabbitmq:
    port: 5672
    username: admin
    password: admin
    virtual-host: admin
    host: 192.168.194.139    
server:
  port: 1234
